apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: managerobo-com-tls
spec:
  secretName: managerobo-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: managerobo.com
  dnsNames:
    - managerobo.com
    - www.managerobo.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - managerobo.com
          - www.managerobo.com